// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOHWqqA20NlnHnHtn19JO4-raKec0OlWQ',
    appId: '1:904291660676:web:77546d9d06d5cea73a63d1',
    messagingSenderId: '904291660676',
    projectId: 'fb-authhh-provider',
    authDomain: 'fb-authhh-provider.firebaseapp.com',
    storageBucket: 'fb-authhh-provider.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuMavVcyKvrPQbstF5qdyNMiLE6gOwAWk',
    appId: '1:904291660676:android:72cefd8022f8ab3f3a63d1',
    messagingSenderId: '904291660676',
    projectId: 'fb-authhh-provider',
    storageBucket: 'fb-authhh-provider.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOHWqqA20NlnHnHtn19JO4-raKec0OlWQ',
    appId: '1:904291660676:web:6a58a71879be33a83a63d1',
    messagingSenderId: '904291660676',
    projectId: 'fb-authhh-provider',
    authDomain: 'fb-authhh-provider.firebaseapp.com',
    storageBucket: 'fb-authhh-provider.firebasestorage.app',
  );

}